project:
  type: book
  output-dir: ../docs

book:
  title: "Learning Diary for Remotely Sensing Cities and Environment"
  author: "Yuqing Niu"
  date: "2/7/2024"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week5.qmd
    - Week6.qmd
    - Week7.qmd
#    - Week8.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

